openai_api_key = "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"
[prompt_canvas]
prompt_words = [
    "Patient is a ",
    "She is ",
    "She has a history of ",
    "She presents with symptoms of ",
    "Examination findings reveal ",
    "Laboratory test results show ",
    "If gender is male ignore pregnent promt.",
    "Analyze everything carefully.",
    "Write the disease in this format (The likely diagnosis for this patient is ) or (Based on the provided information, the likely diagnosis for this patient is )in these format.",
    "Also Proposed treatment in number bullet points"
]

